### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by vashirov** [oskutka/rhlp#13]
All images are missing, server returns error 404.

**Comment by oskutka** [comment]
I'm not quite sure what images are missing? There are not supposed to be any images.

**Comment by vashirov** [comment]
I see this in the web console:
http://rhlp-oskutka.rhcloud.com/pics/stravenky1.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/stravenky2.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/stravenky3.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/banner02.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/cs.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/en.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna1.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna2.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna3.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna7.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna4.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna11.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna9.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/nahledy-jidlo.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/rozvoz-jidel-brno.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/jidelna12.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/no-smoking-symbol.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/preloader.svg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/pics/facebook_pic.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/nav-logo.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/logo.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/thumb1.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/thumb2.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/thumb3.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic5.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic6.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic7.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic8.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic9-1.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic9.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic1.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic2.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/starobrno.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/u-tri-opic3.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/maneo.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/fb.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/illy.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/platebni-karty.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/stravenky.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/img/sponsor/zomato.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/obr/KM_barevne_RGB_CZ.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/obr/cs.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/obr/en.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/obr/icon_doc.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/4-facebook.png Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://rhlp-oskutka.rhcloud.com/obr/icon_pdf.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/5-youtube.png Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://rhlp-oskutka.rhcloud.com/images/logo-tisk.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/cz.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/en.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/jscripts/tiny_mce/plugins/emotions/img/smiley-wink.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/8-zomato.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/7-dobresenajim.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/1-pivovar-dalesice.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/2-pivovar-rohozec.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/images/banery/3-pivovar-svijany.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/templates/Prom/images/logo.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/media/mod_languages/images/cz.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/media/mod_languages/images/en.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/templates/Prom/images/footer-icons.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/logo1.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/logo2.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/sodexho.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/logo3.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/cheque-dejeuner.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/gastro-pass.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://rhlp-oskutka.rhcloud.com/assets/images/design/ticket-restaurant.jpg Failed to load resource: the server responded with a status of 404 (Not Found)

I assumed that they were part of this site.

**Comment by oskutka** [comment]
Well, these images are part of the pages from which the server downloads menus. But they are not used in the resulting page, so nothing is really broken. 

Is there a way to suppress loading the images?

**Comment by vashirov** [comment]
I think they can be stripped from resulting HTML-pages on server (http://rhlp-oskutka.rhcloud.com/$restaurace).
