### ISSUE TITLE
Missing menus for some restaurants

### ISSUE THREAD

**Issue by vashirov** [oskutka/rhlp#15]
Menu is missing from:
A-Sport Hotel
Menza Purkynova (this one might be expected, since there is no menu on their server)
Semilasso

**Comment by oskutka** [comment]
Thanks for reporting the issue.
- I've removed Semilasso (seems out of business) e059df5278e89ec9392325ae3b0ceb678f3d88e5
- Fixed A-Sporthotel  2340e901e132661fee86b9e52bd7e17a15b95b28
- Menza is expected - they don't have menus during summer
