### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by janinko** [oskutka/rhlp#2]
It would be great if you could add a favicon.

**Comment by oskutka** [comment]
That's true. Is there some specific one on your mind?

**Comment by janinko** [comment]
No specific on my mind. I searched a bit and found for example this one free http://icongal.com/gallery/icon/21924/128/dinner_eat_fork_monotone_restaurant_spoon

Maybe an idea - make it in RH color #cc0000

**Comment by oskutka** [comment]
Thanks, that one looks good. I modified it a bit and it's online. I tried also the RH color, but didn't like it.
