### ISSUE TITLE
Adding facebook Cikoria (and Pasta Truck?) lunch menu 

### ISSUE THREAD

**Issue by mareksabo** [oskutka/rhlp#20]
Hi,
it would be nice to have Cikoria menu - although it is posted on [Facebook](https://www.facebook.com/bistro.cikoria/), it shouldn't be a problem to take their last post and simply paste it to rhlp. 
I can try to do it in my leisure time, it is not necessary to have it. 
I was also thinking about pasta truck [lunch menu every tuesday](https://www.facebook.com/pastatruckbrno/) - it is in form of picture on their facebook page which makes it really hard to get their menu in text form. Do you have any ideas how to retrieve it?
Thanks, Marek

**Comment by oskutka** [comment]
Unfortunately it's not that simple. Cikoria restaurant posts more updates onto their Facebook page than just menus, so simply using the last post won't do. You could use some heuristics for that, but that's not easy. 

And yes, Pasta truck is even more difficult. Similarly [Daydream](https://www.facebook.com/daydreamcaffebrno). To be honest, I believe the simplest way would be to ask them to post their menus in text (e.g. to lunchtime.cz).
