### ISSUE TITLE
The menu for 'U kotelny' is not available

### ISSUE THREAD

**Issue by radomirbosak** [oskutka/rhlp#24]
Their menu is now here https://www.zomato.com/widgets/daily_menu.php?entity_id=16506016 (not sure if the url is changing)

**Comment by oskutka** [comment]
The same applies for other Zomato restaurants (Pad Thai, Bavorska and Vista). I'm not sure where the problem is. It works on localhost, but not on OpenShift. They might be blocking the IP address...?

**Comment by tlestach** [comment]
Any chance to contact zomato.com and ask them to whitelist rhcloud? This page does not try to compete with zomato, the purpose is to get a fast overview of lunch opportunities in a specific neighborhood.

**Comment by oskutka** [comment]
I just sent a request to Zomato. Let's hope...

**Comment by jkremser** [comment]
Yeah, they must be blocking the IP, because this fails:
```bash
curl -H "X-Forwarded-For: 54.210.113.18" https://www.zomato.com/cs/widgets/daily_menu.php?entity_id=16506806
```
(`54.210.113.18` was the ip of `rhlp-oskutka.rhcloud.com`)
while this works:
```bash
curl -H "X-Forwarded-For: 8.8.8.8" https://www.zomato.com/cs/widgets/daily_menu.php?entity_id=16506806
```

I am not sure what http client you use, but perhaps this header can be faked (?) Although, it's always better to make a deal with them.

**Comment by oskutka** [comment]
Hi, thanks for the tip. However this header (even though it could be faked) is not sufficient for Zomato to reply. In other words this still doesn't work when invoked from amazon's ip. :-(

And btw - Zomato didn't reply to my request.

**Comment by ogajduse** [comment]
Is it possible to use [Zomato API](https://developers.zomato.com/api) somehow?

**Comment by oskutka** [comment]
@ogajduse Thanks for the pointer. It turned out that this indeed works. So hooray, Zomato restaurants (including U Kotelny) are now functional!
