### ISSUE TITLE
Bufet Brněnka is missing

### ISSUE THREAD

**Issue by lspackova** [oskutka/rhlp#27]
Hi Ondra,
Could you add Bufet Brněnka? http://www.brnenka.cz/detail-doplnkove-sluzby/1/
I tested it several times and it is worth including.
Thanks!
Lenka

**Comment by oskutka** [comment]
Hi Lenka!

Unfortunately Brněnka's menu is on Zomato and Zomato has put rhlp's ip address on their blacklist, so it wouldn't work (at least on rh-cloud).

Thanks for the suggestion though!

Ondra

**Comment by oskutka** [comment]
Zomato restaurants now work. I added Brněnka to the list (you might need to Ctrl-F5 to see it).
