### ISSUE TITLE
please add Menza Kolejni, Studentska jidelna FCH and Pizzerie Mozzarella

### ISSUE THREAD

**Issue by zdohnal** [oskutka/rhlp#30]
Hi,

would you mind adding these student cafeterias - Pizzerie Mozzarella http://www.kam.vutbr.cz/?p=menu&provoz=18 , Menza Kolejni http://www.kam.vutbr.cz/?p=menu&provoz=20 and Studenska jidelna FCH http://www.kam.vutbr.cz/?p=menu&provoz=16 ?

**Comment by oskutka** [comment]
Thanks for reporting the issue!

**Comment by zdohnal** [comment]
And would it be possible add menza menu (one from libreoffice document http://www.kam.vutbr.cz/skripty/doc.aspx?id=506&d=20171018 ) too?
