### ISSUE TITLE
Menu for Pad Thai

### ISSUE THREAD

**Issue by hyperlamacz** [oskutka/rhlp#33]
The daily menu for Pad Thai does not work at the moment. It can be found here: https://www.zomato.com/brno/pad-thai-kr%C3%A1lovo-pole-brno-sever/daily-menu

**Comment by oskutka** [comment]
Unfortunately Pad Thai uses Zomato, which blocks requests from OpenShift. See Issue #24 for details.

**Comment by hyperlamacz** [comment]
Thanks, this is clearly a duplicate, closing.
