### ISSUE TITLE
cookpoint menu is now showed in english

### ISSUE THREAD

**Issue by zdohnal** [oskutka/rhlp#34]
Hi,
suddenly cookpoint menu is showed in english. Is it intentional or a bug (because all other menus are in Czech)? If it is a bug, would you mind showing it in Czech again?

**Comment by oskutka** [comment]
Unfortunately Cookpoint changed their default language to English. To see the page properly in Czech, one needs to first go to http://cookpoint.cz/lang/1 and only then load the main page with the acquired cookie. I'll fix it in foreseeable future.
