### ISSUE TITLE
Winston menu is not showed

### ISSUE THREAD

**Issue by zdohnal** [oskutka/rhlp#35]
Hi,

Winston started to show "Pro tento den nebylo zadáno menu", but the menu is available on the crocus site. Would you mind looking into it?

**Comment by oskutka** [comment]
The menu is retrieved from this site:
https://www.menicka.cz/3875-pekarna-crocus-s.r.o..html
There really is no menu for this week. 

Theoretically we can parse the .doc files that are at their pages, but I hope that the menu at menicka.cz will be all right next week.

**Comment by zdohnal** [comment]
Ok, I thought you used .doc . Let's hope menicka.cz will update :)

**Comment by oskutka** [comment]
Indeed, menicka.cz was updated and the menu is now properly shown.
