### ISSUE TITLE
Application is not available error

### ISSUE THREAD

**Issue by yarda** [oskutka/rhlp#51]
This started to happen recently. On the first rhlp access the following error is shown:

```
Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

    The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
    The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
    Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
```
Upon refresh, it shows OK. It happens quite often and is possible to reproducer from different machines.

**Comment by zdohnal** [comment]
The same issue happens for me too.

**Comment by oskutka** [comment]
This looks like an infrastructure problem of the cluster RHLP is running on. More specifically it could be this one: https://bugzilla.redhat.com/show_bug.cgi?id=1522812, but I'm no expert here.

I'm afraid there's nothing much I can do about that (apart from deploying RHLP to a different cluster).

**Comment by oskutka** [comment]
This has been fixed. However the current deployment has different problems...
